Repository MewsSystems/fiscalizations, pull requests merged in 2021-11, with the labels that each got.

#93 Extended Fiskaly error response DTO with ServerError
  src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
  src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
  src/Germany/Mews.Fiscalizations.Germany/V2/Dto/FiskalyErrorResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/ErrorResult.cs
  src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/FiskalyError.cs
Labels: easyfix, finance, tested

#95 Fixed nuget properties.
  packageIcon.png
  src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
  src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
  src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj
  src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
  src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
  src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
Labels: easyfix, finance, tested

#96 Removed Germany v1
  .github/workflows/build-and-test-all-linux.yml
  .github/workflows/build-and-test-all-windows.yml
  .github/workflows/build-and-test-germany-linux.yml
  .github/workflows/build-and-test-germany-windows.yml
  .github/workflows/publish-germany.yml
  src/Germany/Mews.Fiscalizations.Germany.Tests/V1/ClientTests.cs
  src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TestFixture.cs
  src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TransactionTests.cs
  src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TssTests.cs
  src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
  src/Germany/Mews.Fiscalizations.Germany/V1/Client.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/AuthorizationTokenRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/AuthorizationTokenResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/ClientResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/CreateClientRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/CreateTssRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/FinishTransactionRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/FiskalyErrorResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/TransactionRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/TransactionResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/TssResponse.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Dto/UpdateTssRequest.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/FiskalyClient.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/AccessToken.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Bill.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Client.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Item.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Payment.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Result/ErrorResult.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Result/FiskalyError.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Result/ResponseResult.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Signature.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Transaction.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/TransactionState.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Tss.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Types/ApiKey.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/Model/Types/ApiSecret.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/ModelMapper.cs
  src/Germany/Mews.Fiscalizations.Germany/V1/RequestCreator.cs
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
Labels: finance

#92 Updated FuncSharp library to the latest version 4.0.0
  src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
  src/Core/Mews.Fiscalizations.Core/Model/Collections/Sequence.cs
  src/Core/Mews.Fiscalizations.Core/Model/Collections/SequenceStartingWithOne.cs
  src/Core/Mews.Fiscalizations.Core/Model/Collections/SequenceStartingWithZero.cs
  src/Core/Mews.Fiscalizations.Core/Model/Error.cs
  src/Core/Mews.Fiscalizations.Core/Model/Extensions/ITryExtensions.cs
  src/Core/Mews.Fiscalizations.Core/Model/Legal/EuropeanUnionTaxpayerIdentificationNumber.cs
  src/Core/Mews.Fiscalizations.Core/Model/Legal/NonEuropeanUnionTaxpayerIdentificationNumber.cs
  src/Core/Mews.Fiscalizations.Core/Model/Legal/TaxpayerIdentificationNumber.cs
  src/Core/Mews.Fiscalizations.Core/Model/Numbers/NonNegativeInt.cs
  src/Core/Mews.Fiscalizations.Core/Model/Numbers/PositiveInt.cs
  src/Core/Mews.Fiscalizations.Core/Model/Strings/NonEmptyNorWhitespaceString.cs
  src/Core/Mews.Fiscalizations.Core/Model/Strings/NonEmptyString.cs
  src/Core/Mews.Fiscalizations.Core/Model/Strings/String1To50.cs
  src/Core/Mews.Fiscalizations.Core/Validations/DecimalValidations.cs
  src/Core/Mews.Fiscalizations.Core/Validations/IComparableValidations.cs
  src/Core/Mews.Fiscalizations.Core/Validations/IntValidations.cs
  src/Core/Mews.Fiscalizations.Core/Validations/ObjectValidations.cs
  src/Core/Mews.Fiscalizations.Core/Validations/StringValidations.cs
  src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
  src/Germany/Mews.Fiscalizations.Germany/V2/Model/Types/ApiKey.cs
  src/Germany/Mews.Fiscalizations.Germany/V2/Model/Types/ApiSecret.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/ForeignCompany.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/LocalCompany.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/Receiver.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/AdditionalAddressDetail.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/City.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/CurrencyCode.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/Description.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/EncryptionKey.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/ExchangeRate.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/InvoiceNumber.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/Login.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/Name.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/PostalCode.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/Region.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/SigningKey.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/VatCode.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Models/ValidationExtensions.cs
  src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
  src/Mews.Fiscalizations.All.props
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/InvoicesToSubmit.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/OperationTypeTaxBreakdown.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/SimplifiedInvoicesToSubmit.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/TaxSummary.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/Amount.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/Name.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/Percentage.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/String0To500.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/String1To20.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/String1To60.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/Year.cs
Labels: finance, tested

#97 Introduce soap action error handling, part 1
  src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs
  src/Spain/Mews.Fiscalizations.Spain/Client.cs
  src/Spain/Mews.Fiscalizations.Spain/Communication/SoapClient.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFaultResponse.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ErrorResult.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ResponseResult.cs
  src/Spain/Mews.Fiscalizations.Spain/Nif/NifValidator.cs
Labels: finance

#99 Introduce soap action error handling, part 2.1
  src/Spain/Mews.Fiscalizations.Spain.Tests/SoapFaultResponseDeserializationTests.cs
  src/Spain/Mews.Fiscalizations.Spain/AssemblyInfo.cs
  src/Spain/Mews.Fiscalizations.Spain/Client.cs
  src/Spain/Mews.Fiscalizations.Spain/Communication/SoapClient.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFault/SoapFaultResponse.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFault/SoapFaultResultBody.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFault/SoapFaultResultBodyFault.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFault/SoapFaultResultBodyFaultDetail.cs
  src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFaultResponse.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ResponseResult.cs
  src/Spain/Mews.Fiscalizations.Spain/Nif/NifValidator.cs
Labels: finance

#101 Introduce soap action error handling, part 3
  src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs
  src/Spain/Mews.Fiscalizations.Spain.Tests/SoapFaultResponseDeserializationTests.cs
  src/Spain/Mews.Fiscalizations.Spain/Client.cs
  src/Spain/Mews.Fiscalizations.Spain/Communication/SoapClient.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ErrorResult.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ResponseResult.cs
  src/Spain/Mews.Fiscalizations.Spain/Nif/NifValidator.cs
Labels: finance

#102 Introduce soap action error handling, part 4
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
Labels: finance

#103 Introduce soap action error handling, part 6
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/AssemblyInfo.cs
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
  src/Spain/README.md
Labels: easyfix, finance
