Repository MewsSystems/fiscalizations, pull requests merged in 2022-01, with the labels that each got.

#108 Add response logging on Nif validator
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
  src/Spain/Mews.Fiscalizations.Spain/Nif/NifValidator.cs
Labels: easyfix, finance

#109 Introduced Uniwix error handling
  src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
  src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorResult.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorType.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/UniwixAuthorizationException.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/UniwixConnectionException.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/UniwixErrorCodes.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/UniwixException.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/UniwixValidationException.cs
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
Labels: finance

#111 Handling of italian fiscal registry error code "-12"
  src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
  src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorType.cs
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
Labels: easyfix, finance, tested
