Repository MewsSystems/fiscalizations, pull requests merged in 2022-04, with the labels that each got.

#115 Updated SII test environment domain.
  .github/workflows/build-and-test-all-linux.yml
  .github/workflows/build-and-test-italy-linux.yml
  .github/workflows/build-and-test-spain-linux.yml
  .github/workflows/publish-all.yml
  .github/workflows/publish-italy.yml
  .github/workflows/publish-spain.yml
  README.md
  src/Austria/Mews.Fiscalizations.Austria.Tests/ATrustSignerTests.cs
  src/Spain/Mews.Fiscalizations.Spain/Client.cs
Labels: easyfix, tested, b2b.expansion

#114 Add errortype for spain soap
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
  src/Spain/Mews.Fiscalizations.Spain/Model/Enums/ErrorType.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Response/ErrorResult.cs
Labels: easyfix, b2b.expansion, Abdal :+1:

#116 Fixed Ireland tax payer number validation regex.
  src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
  src/Core/Mews.Fiscalizations.Core/Model/Countries/Countries.cs
  src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
Labels: easyfix, tested, b2b.expansion, Abdal :+1:

#117 Improved Spain foreign party validations
  src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
  src/Core/Mews.Fiscalizations.Core/Model/Countries/Country.cs
  src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
  src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs
  src/Spain/Mews.Fiscalizations.Spain/Converters/ModelToDtoConverter.cs
  src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
  src/Spain/Mews.Fiscalizations.Spain/Model/Enums/ResidenceCountryIdentificatorType.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/CounterParty.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/CounterPartyCompany.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/ForeignCompany.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/ForeignCounterParty.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/ForeignCustomer.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/Header.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/Invoice.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/LocalCompany.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Request/LocalCounterParty.cs
  src/Spain/Mews.Fiscalizations.Spain/Model/Types/ForeignTaxpayerNumber.cs
Labels: easyfix, tested, b2b.expansion, Abdal :+1:

#119 Added A-Trust test account and enabled the tests back.
  .github/workflows/build-and-test-all-linux.yml
  .github/workflows/build-and-test-all-windows.yml
  .github/workflows/build-and-test-austria-linux.yml
  .github/workflows/build-and-test-austria-windows.yml
  .github/workflows/publish-all.yml
  .github/workflows/publish-austria.yml
  src/Austria/Mews.Fiscalizations.Austria.Tests/ATrustSignerTests.cs
  src/Austria/Mews.Fiscalizations.Austria/Dto/Receipt.cs
Labels: easyfix, tested, b2b.expansion, Abdal :+1:
